# Site settings

title: 개발 참고서
tagline: 'tag line'
email: vvic90vk@gmail.com
name: Victory Kim
description: >
  참고가 안되는 참고서
baseurl: ""
url: "https://victoryKim.github.io"

# Build settings
markdown:         kramdown
highlighter:      rouge

paginate: 5
# paginate_path: "/page:num/"
# inter_post_navigation: false

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

sidebar_home_link:  true