# External gems
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
plugins:
  - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap
  - jekyll-paginate

# Site settings
title: 개발 참고서
email: vvic90vk@gmail.com
name: Victory Kim
description: >
  참고가 안되는 참고서
baseurl: ""
url: ""

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: false
highlightjs_theme: "atom-one-dark"

# Disqus comments
disqus_shortname: gitHub-jekyll